### PR TITLE
Initial Aluminum dubbing

### PR DESCRIPTION
**Pull request by andy-yoo**
Changes are made to enable the use of Aluminum for more efficeint collectives.

### CODE REVIEW

**Comment by andy-yoo** [comment]
It appears that I have no privilege to merge this commit.

**Comment by ndryden** [comment]
@andy-yoo I took a look at this since it's integrating Aluminum. Some thoughts:
* Aluminum should have a working CMake build soon, it probably makes sense to integrate with that. Dylan or Tom can probably help you with the CMake stuff if needed.
* I don't think we should be copying LBANN's `base.hpp` directly. I'm not sure why we need that at all, since it's just typedefs for Hydrogen/Elemental things anyway, and within Hydrogen, we should stick with their naming standard. (There's also possibly license issues.)
* Ditto for `hydrogen.hpp`/`hydrogen.cpp`. If we need something specific from that, we should just move over the parts that we need.
* I'm not sure why we're adding `mpi_collectives.hpp` instead of keeping things contained within `mpi.hpp`/`mpi.cpp`.
* In `environment.cpp`, I'm not sure whether we can move the initialization of CUDA to after MPI initialization. I recall there was something particular about the order there, perhaps @benson31 can confirm.
* We should make sure to stick to the Elemental/Hydrogen coding style-- it's slightly different from LBANN's.

**Comment by benson31** [comment]
@andy-yoo , is this at a point where it should be reviewed? Or are you still working on it?

**Comment by andy-yoo** [comment]
Tom,

I think this PR can be discarded, as the latest changes I made took care of Nikoli’s comment.

**Pull request closed without merging**
