### PR TITLE
Hack in an impl of TransposeDist that should work for GPUs

### PR DESCRIPTION
**Pull request by benson31**
Should fix @samadejacobs issue with TransposeDist for GPU matrices

### CODE REVIEW

**Comment by benson31** [comment]
@samadejacobs If you could confirm this fixes your issue, that'd be awesome. Thanks!

**Comment by benson31** [comment]
I've also updated `ColAllGather` since that was going to be another issue and was a similar change.

**Comment by samadejacobs** [comment]
I edited my copy build/hydrogen/CMakeList to pull from your commit (#5005258), recompiled LBANN but I am still getting the same error as earlier reported.

**Comment by benson31** [comment]
Is it possible for me to run what you're running? If so, can you send me the command line?

It should not be possible to get the same error since I deleted the line that generates the error...

**Comment by benson31** [comment]
Oh also, you will need to change the `Hydrogen_URL` to point to my fork and then `Hydrogen_TAG` to be `fix-transpose-dist`.

**Comment by samadejacobs** [comment]
Code runs without crashing except that the results are incorrect, posted as a separate [LBANN issue](https://github.com/LLNL/lbann/issues/530)

**Review by samadejacobs — APPROVED** [review]
Please see previous comment.

**Comment by benson31** [comment]
Ok, I'm going to merge this and address the correctness issue in a separate branch. It's work in progress to write correctness tests for the dark corners of Copy.

**Pull request merged**
