### PR TITLE
Rework the Comm interface within Hydrogen

### PR DESCRIPTION
**Pull request by benson31**
If not using Aluminum, nothing should really change.

If using Aluminum, things change. This encapsulates a lazy-evaluation model of communicator construction. For each `cudaStream_t, MPI_Comm, Al::Backend` triplet, we associate a unique `Al::Communicator` object which is created the first time it is requested. It is then cached for later use.

This branch actually builds off another branch where I was doing some maintenance-y things. If folks strongly prefer, I can separate that into another PR, but they aren't super-sweeping changes.

### CODE REVIEW

**Comment by benson31** [comment]
There are a few compatibility issues with LBANN.
1. The CPU-backend can be safely worked around by 7d45590, but this should not be a permanent fixture.
2. The use of `some_comm.comm` should have gone away as soon as Aluminum was introduced to Hydrogen and it's my fault it didn't. Now that the Comm objects might have complicated state, I'm not ok with this being public and it should be wrapped in an accessor. (Basically, if you can get it out by reference, you might change it, corrupting the aluminum communicators.) That brings us to LBANN. There aren't many instances, but we do access the raw `MPI_Comm` this way. There's no back-compatibility fix for that.
3. There is one instance of the `static_assert` in 7d45590 firing for a GPU build, so at least one instance needs to update in a non-backward-compatible way.

**Comment by benson31** [comment]
Also, while this appears to be building just fine with `MPI-CUDA` backend enabled, it hangs at runtime. I'm guessing this is the ordering of collectives on each communicator nonsense. IMO this is Aluminum's issue since it calls `MPI_Comm_dup` opaquely, but we should discuss. But before we get into that too deeply, I'm verifying that this is indeed the issue.

**Comment by benson31** [comment]
This change appears to pipe a bunch of work to the default stream. I have no idea. Working on it. Will relabel when that's resolved.

**Comment by benson31** [comment]
Ok. Let's try this. I have confirmed it works with my Gemm tests. Haven't tried LBANN yet. It's building presently.

**Comment by benson31** [comment]
Oh yeah, this breaks the API, so LBANN won't build.

**Review by ndryden — APPROVED** [review]
Tested on Lassen, looks good to me.

**Review by naoyam — APPROVED** [review]
Works with the distconv branch as well.

**Pull request merged**
