### PR TITLE
Fix gcc 8 build

### PR DESCRIPTION
**Pull request by benson31**

### CODE REVIEW

**Review by timmoon10 — APPROVED** [review]
I don't see anything suspect. It build fine for me.

**Comment by benson31** [comment]
This actually doesn't work with GPU support enabled. I will reopen when I resolve those issues. They're bad, though. This compiler is so broken.

**Comment by benson31** [comment]
Ok, I think this works now.

**Comment by benson31** [comment]
Unfortunately, I ended up reworking some interface things. Not ideal, not strictly necessary, but I think the MPI interface is a bit more streamlined now. So this actually includes a huge breaking change -- that has been fixed -- to the `SyncInfo` semantics. It probably breaks some of LBANN code as well, so I will need to verify and correct that.

**Review by timmoon10 — APPROVED** [review]
LGTM.

**Review by bvanessen — APPROVED** [review]

**Comment by benson31** [comment]
Here we go. :crossed_fingers:

**Pull request merged**
